/**
 * CLARION Session Report Export Utility
 * Generates and downloads a structured JSON report file.
 * No user input text is ever included — only metadata and verdicts.
 */

/**
 * Generates and triggers download of a CLARION session report.
 * @param {Object} reportData - The structured report data.
 * @param {string} filename - Output filename without extension.
 */
export function downloadReport(reportData, filename) {
  const report = {
    generated_by: 'CLARION Digital Public Safety Platform',
    generated_at: new Date().toISOString(),
    report_version: '1.0',
    disclaimer:
      'This report was generated by an AI-assisted analysis tool. Results should be verified by appropriate authorities before use in formal proceedings.',
    ...reportData,
  }

  const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${filename}_${Date.now()}.json`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
